export const LOGOUT_SUBSCRIPTION = "LOGOUT_SUBSCRIPTION";

export const FETCH_PLAN_INFO = "FETCH_PLAN_INFO";
export const CHOOSE_MEALS_EACH_DELIVERY = "CHOOSE_MEALS_EACH_DELIVERY";
export const CHOOSE_PAYMENT_OPTION = "CHOOSE_PAYMENT_OPTION";
export const GET_TOTAL_PAYMENT = "GET_TOTAL_PAYMENT";

// CHOOSE PLAN PAGE VARIABLES
export const FETCH_PROFILE_INFO = "FETCH_PROFILE_INFO";
export const CHANGE_ADDRESS_FIRST_NAME = "CHANGE_ADDRESS_FIRST_NAME";
export const CHANGE_ADDRESS_LAST_NAME = "CHANGE_ADDRESS_LAST_NAME";
export const CHANGE_ADDRESS_STREET = "CHANGE_ADDRESS_STREET";
export const CHANGE_ADDRESS_UNIT = "CHANGE_ADDRESS_UNIT";
export const CHANGE_ADDRESS_CITY = "CHANGE_ADDRESS_CITY";
export const CHANGE_ADDRESS_STATE = "CHANGE_ADDRESS_STATE";
export const CHANGE_ADDRESS_ZIP = "CHANGE_ADDRESS_ZIP";
export const CHANGE_ADDRESS_PHONE = "CHANGE_ADDRESS_PHONE";
export const CHANGE_DELIVERY_INSTRUCTIONS = "CHANGE_DELIVERY_INSTRUCTIONS";
export const CHANGE_PAYMENT_PASSWORD = "CHANGE_PAYMENT_PASSWORD";
export const CHANGE_CARD_NUMBER = "CHANGE_CARD_NUMBER";
export const CHANGE_CARD_CVV = "CHANGE_CARD_CVV";
export const CHANGE_CARD_ZIP = "CHANGE_CARD_ZIP";
export const CHANGE_CARD_MONTH = "CHANGE_CARD_MONTH";
export const CHANGE_CARD_YEAR = "CHANGE_CARD_YEAR";
export const ADD_ERROR = "ADD_ERROR";
export const SUBMIT_PAYMENT = "SUBMIT_PAYMENT";

// MEAL PLAN PAGE VARIABLES
export const FETCH_SUBSCRIBED_INFO = "FETCH_SUBSCRIBED_INFO";
